# Site settings
title: Victor Marinescu
description: 'Victor Marinescu - Personal Blog'
url: 'https://victor.marinescu.ch'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Victor Marinescu'
  email: victor@marinescu.ch
  twitter_username: MarinescuV1ctor
  facebook_username: victor.marinescu.101
  github_username:  marinescuvictor
  linkedin_username:  victor-marinescu-1ba783159

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
